name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Linux
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build with Cargo
        run: cargo build --release --target x86_64-unknown-linux-gnu
  
    name: Build Windows
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Build with Cargo
        run: cargo build --release --target x86_64-pc-windows-gnu
